
// ============================================
// logs.js - COMPREHENSIVE LOGGING SYSTEM
// ============================================

// ===== LOG STORAGE =====
const logStore = {
  logs: [],
  
  // Add log entry
  addLog: function(category, action, details, status = 'SUCCESS', memberId = null) {
    const logEntry = {
      id: `log_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: new Date().toISOString(),
      date: new Date().toLocaleDateString('en-US'),
      time: new Date().toLocaleTimeString('en-US'),
      category: category,
      action: action,
      details: details,
      status: status,
      memberId: memberId || window.appState?.member?.id,
      memberName: window.appState?.member?.fullName || 'System',
      userRole: window.appState?.role || 'UNKNOWN'
    };
    
    this.logs.push(logEntry);
    localStorage.setItem('clubLogs', JSON.stringify(this.logs));
    console.log(`📝 Log added: ${category} - ${action}`);
    return logEntry;
  },

  // Get all logs
  getAllLogs: function() {
    return this.logs;
  },

  // Filter logs by criteria
  filterLogs: function(filters = {}) {
    return this.logs.filter(log => {
      if (filters.category && log.category !== filters.category) return false;
      if (filters.action && log.action !== filters.action) return false;
      if (filters.status && log.status !== filters.status) return false;
      if (filters.memberId && log.memberId !== filters.memberId) return false;
      if (filters.dateFrom && new Date(log.timestamp) < new Date(filters.dateFrom)) return false;
      if (filters.dateTo && new Date(log.timestamp) > new Date(filters.dateTo)) return false;
      return true;
    });
  },

  // Load logs from storage
  loadLogs: function() {
    const stored = localStorage.getItem('clubLogs');
    if (stored) {
      this.logs = JSON.parse(stored);
    }
  }
};

// Load logs on initialization
logStore.loadLogs();

// ===== 1. LOGIN & AUTHENTICATION LOGS =====
export function logLoginEvent(email, status = 'SUCCESS', details = '') {
  logStore.addLog(
    'LOGIN',
    'User Login',
    `Email: ${email}; ${details}`,
    status
  );
}

export function logLogoutEvent() {
  logStore.addLog(
    'LOGIN',
    'User Logout',
    `User logged out from member portal`,
    'SUCCESS'
  );
}

export function logPasswordChange(email, status = 'SUCCESS') {
  logStore.addLog(
    'LOGIN',
    'Password Changed',
    `Password updated for: ${email}`,
    status
  );
}

export function logFailedLoginAttempt(email, reason = 'Invalid credentials') {
  logStore.addLog(
    'LOGIN',
    'Failed Login Attempt',
    `Email: ${email}; Reason: ${reason}`,
    'FAILED'
  );
}

export function logAccountActivation(fullName, phone, status = 'SUCCESS') {
  logStore.addLog(
    'LOGIN',
    'Account Activation',
    `Name: ${fullName}; Phone: ${phone}`,
    status
  );
}

// ===== 2. ACCOUNT ACTIVATION LOGS =====
export function logAccountActivationRequest(fullName, phone) {
  logStore.addLog(
    'ACCOUNT_ACTIVATION',
    'Activation Request',
    `Pre-registered member activation: ${fullName}`,
    'PENDING'
  );
}

export function logAccountActivationComplete(fullName, phone) {
  logStore.addLog(
    'ACCOUNT_ACTIVATION',
    'Activation Complete',
    `Account activated for: ${fullName}; Phone: ${phone}`,
    'SUCCESS'
  );
}

export function logAccountActivationFailed(fullName, reason) {
  logStore.addLog(
    'ACCOUNT_ACTIVATION',
    'Activation Failed',
    `Failed for: ${fullName}; Reason: ${reason}`,
    'FAILED'
  );
}

// ===== 3. ATTENDANCE LOGS =====
export function logAttendanceMarked(memberId, memberName, sessionId, status, timestamp = new Date()) {
  logStore.addLog(
    'ATTENDANCE',
    `Attendance - ${status}`,
    `Member: ${memberName}; Session: ${sessionId}; Status: ${status}; Time: ${timestamp.toLocaleTimeString()}`,
    'SUCCESS',
    memberId
  );
}

export function logAttendanceOverride(memberId, memberName, sessionId, oldStatus, newStatus, adminName) {
  logStore.addLog(
    'ATTENDANCE',
    'Attendance Override',
    `Member: ${memberName}; Session: ${sessionId}; Changed from ${oldStatus} to ${newStatus}; By: ${adminName}`,
    'SUCCESS',
    memberId
  );
}

export function logSessionAttendanceFinalized(sessionId, presentCount, totalCharge, perPlayerCharge) {
  logStore.addLog(
    'ATTENDANCE',
    'Session Finalized',
    `Session: ${sessionId}; Present: ${presentCount}; Total Charge: ${totalCharge} Fils; Per Player: ${perPlayerCharge} Fils`,
    'SUCCESS'
  );
}

export function logAttendanceReport(flightId, reportType, generatedBy) {
  logStore.addLog(
    'ATTENDANCE',
    'Report Generated',
    `Flight: ${flightId}; Type: ${reportType}; Generated by: ${generatedBy}`,
    'SUCCESS'
  );
}

// ===== 4. TIMETABLE LOGS =====
export function logTimetableCreated(day, startTime, endTime, activity, flight) {
  logStore.addLog(
    'TIMETABLE',
    'Session Created',
    `Day: ${day}; Time: ${startTime}-${endTime}; Activity: ${activity}; Flight: ${flight}`,
    'SUCCESS'
  );
}

export function logTimetableModified(sessionId, changes) {
  logStore.addLog(
    'TIMETABLE',
    'Session Modified',
    `Session: ${sessionId}; Changes: ${changes}`,
    'SUCCESS'
  );
}

export function logTimetableDeleted(sessionId, day, time) {
  logStore.addLog(
    'TIMETABLE',
    'Session Deleted',
    `Session: ${sessionId}; Day: ${day}; Time: ${time}`,
    'SUCCESS'
  );
}

export function logMonthPublished(month, sessionCount) {
  logStore.addLog(
    'TIMETABLE',
    'Month Published',
    `Month: ${month}; Sessions Created: ${sessionCount}`,
    'SUCCESS'
  );
}

export function logBulkTimetableImport(rowCount, successCount, failedCount) {
  logStore.addLog(
    'TIMETABLE',
    'Bulk Import',
    `Total Rows: ${rowCount}; Success: ${successCount}; Failed: ${failedCount}`,
    failedCount === 0 ? 'SUCCESS' : 'PARTIAL'
  );
}

// ===== 5. WALLET & PAYMENTS LOGS =====
export function logPaymentSubmitted(memberId, memberName, amount, method, reference) {
  logStore.addLog(
    'WALLET',
    'Payment Submitted',
    `Member: ${memberName}; Amount: ${amount} BHD; Method: ${method}; Reference: ${reference}`,
    'PENDING',
    memberId
  );
}

export function logPaymentVerified(memberId, memberName, amount, verifiedBy) {
  logStore.addLog(
    'WALLET',
    'Payment Verified',
    `Member: ${memberName}; Amount: ${amount} BHD; Verified by: ${verifiedBy}`,
    'SUCCESS',
    memberId
  );
}

export function logPaymentFailed(memberId, memberName, amount, reason) {
  logStore.addLog(
    'WALLET',
    'Payment Failed',
    `Member: ${memberName}; Amount: ${amount} BHD; Reason: ${reason}`,
    'FAILED',
    memberId
  );
}

export function logWalletCreditAdded(memberId, memberName, amount, addedBy) {
  logStore.addLog(
    'WALLET',
    'Credit Added',
    `Member: ${memberName}; Amount: +${amount} BHD; Added by: ${addedBy}`,
    'SUCCESS',
    memberId
  );
}

export function logWalletCreditDeducted(memberId, memberName, amount, reason, deductedBy) {
  logStore.addLog(
    'WALLET',
    'Credit Deducted',
    `Member: ${memberName}; Amount: -${amount} BHD; Reason: ${reason}; Deducted by: ${deductedBy}`,
    'SUCCESS',
    memberId
  );
}

export function logWalletBalanceSnapshot(memberId, memberName, balance) {
  logStore.addLog(
    'WALLET',
    'Balance Snapshot',
    `Member: ${memberName}; Balance: ${balance} BHD`,
    'SUCCESS',
    memberId
  );
}

export function logGameCostCharged(memberId, memberName, sessionId, chargeAmount) {
  logStore.addLog(
    'WALLET',
    'Game Cost Charged',
    `Member: ${memberName}; Session: ${sessionId}; Charge: ${chargeAmount} BHD`,
    'SUCCESS',
    memberId
  );
}

// ===== 6. SESSION CONTROL LOGS =====
export function logSessionStarted(sessionId, activity, flight, expectedAttendees) {
  logStore.addLog(
    'SESSION',
    'Session Started',
    `Session: ${sessionId}; Activity: ${activity}; Flight: ${flight}; Expected: ${expectedAttendees}`,
    'SUCCESS'
  );
}

export function logSessionCompleted(sessionId, presentCount, totalCost, perPlayerCost) {
  logStore.addLog(
    'SESSION',
    'Session Completed',
    `Session: ${sessionId}; Present: ${presentCount}; Total Cost: ${totalCost} Fils; Per Player: ${perPlayerCost} Fils`,
    'SUCCESS'
  );
}

export function logMemberAddedToSession(sessionId, memberId, memberName, addedBy) {
  logStore.addLog(
    'SESSION',
    'Member Added',
    `Session: ${sessionId}; Member: ${memberName}; Added by: ${addedBy}`,
    'SUCCESS',
    memberId
  );
}

export function logMemberRemovedFromSession(sessionId, memberId, memberName, removedBy) {
  logStore.addLog(
    'SESSION',
    'Member Removed',
    `Session: ${sessionId}; Member: ${memberName}; Removed by: ${removedBy}`,
    'SUCCESS',
    memberId
  );
}

export function logShuttlesUsedRecorded(sessionId, shuttleCount, tubePrice, totalCost) {
  logStore.addLog(
    'SESSION',
    'Shuttles Recorded',
    `Session: ${sessionId}; Shuttles: ${shuttleCount}; Tube Price: ${tubePrice} BHD; Total Cost: ${totalCost} Fils`,
    'SUCCESS'
  );
}

export function logPaymentStatusUpdated(sessionId, memberId, memberName, oldStatus, newStatus) {
  logStore.addLog(
    'SESSION',
    'Payment Status Updated',
    `Session: ${sessionId}; Member: ${memberName}; Status: ${oldStatus} → ${newStatus}`,
    'SUCCESS',
    memberId
  );
}

// ===== 7. SHUTTLE STOCK LOGS =====
export function logStockAdded(itemType, quantity, addedBy) {
  logStore.addLog(
    'SHUTTLE',
    'Stock Added',
    `Item: ${itemType}; Quantity: +${quantity}; Added by: ${addedBy}`,
    'SUCCESS'
  );
}

export function logStockDeducted(itemType, quantity, reason, deductedBy) {
  logStore.addLog(
    'SHUTTLE',
    'Stock Deducted',
    `Item: ${itemType}; Quantity: -${quantity}; Reason: ${reason}; Deducted by: ${deductedBy}`,
    'SUCCESS'
  );
}

export function logStockLow(itemType, currentStock, minimumThreshold) {
  logStore.addLog(
    'SHUTTLE',
    'Low Stock Alert',
    `Item: ${itemType}; Current: ${currentStock}; Minimum: ${minimumThreshold}`,
    'WARNING'
  );
}

export function logTubePriceUpdated(oldPrice, newPrice, updatedBy) {
  logStore.addLog(
    'SHUTTLE',
    'Tube Price Updated',
    `Old Price: ${oldPrice} BHD; New Price: ${newPrice} BHD; Updated by: ${updatedBy}`,
    'SUCCESS'
  );
}

export function logStockInventorySnapshot(itemType, totalCount, goodCount, repairCount, damagedCount) {
  logStore.addLog(
    'SHUTTLE',
    'Inventory Snapshot',
    `Item: ${itemType}; Total: ${totalCount}; Good: ${goodCount}; Repair: ${repairCount}; Damaged: ${damagedCount}`,
    'SUCCESS'
  );
}

export function logStockTransfer(itemType, quantity, fromFlight, toFlight, transferredBy) {
  logStore.addLog(
    'SHUTTLE',
    'Stock Transfer',
    `Item: ${itemType}; Quantity: ${quantity}; From: ${fromFlight}; To: ${toFlight}; By: ${transferredBy}`,
    'SUCCESS'
  );
}

// ===== MEMBER MANAGEMENT LOGS =====
export function logMemberCreated(fullName, phone, role, flight, createdBy) {
  logStore.addLog(
    'MEMBER',
    'Member Created',
    `Name: ${fullName}; Phone: ${phone}; Role: ${role}; Flight: ${flight}; Created by: ${createdBy}`,
    'SUCCESS'
  );
}

export function logMemberUpdated(memberId, memberName, changes, updatedBy) {
  logStore.addLog(
    'MEMBER',
    'Member Updated',
    `Member: ${memberName}; Changes: ${changes}; Updated by: ${updatedBy}`,
    'SUCCESS',
    memberId
  );
}

export function logMemberDeleted(memberId, memberName, deletedBy) {
  logStore.addLog(
    'MEMBER',
    'Member Deleted',
    `Member: ${memberName}; Deleted by: ${deletedBy}`,
    'SUCCESS',
    memberId
  );
}

export function logMemberStatusChanged(memberId, memberName, oldStatus, newStatus, changedBy) {
  logStore.addLog(
    'MEMBER',
    'Status Changed',
    `Member: ${memberName}; Status: ${oldStatus} → ${newStatus}; Changed by: ${changedBy}`,
    'SUCCESS',
    memberId
  );
}

// ===== ACTIVITY LOGS =====
export function logActivityCreated(activityName, createdBy) {
  logStore.addLog(
    'ACTIVITY',
    'Activity Created',
    `Activity: ${activityName}; Created by: ${createdBy}`,
    'SUCCESS'
  );
}

export function logFlightCreated(activityName, flightName, createdBy) {
  logStore.addLog(
    'ACTIVITY',
    'Flight Created',
    `Activity: ${activityName}; Flight: ${flightName}; Created by: ${createdBy}`,
    'SUCCESS'
  );
}

// ===== ADMIN ACTIONS LOGS =====
export function logAdminAction(action, details, adminName) {
  logStore.addLog(
    'ADMIN',
    action,
    `${details}; Performed by: ${adminName}`,
    'SUCCESS'
  );
}

export function logAdsApproved(businessName, offer, approvedBy) {
  logStore.addLog(
    'ADS',
    'Ad Approved',
    `Business: ${businessName}; Offer: ${offer}; Approved by: ${approvedBy}`,
    'SUCCESS'
  );
}

export function logAdsRejected(businessName, reason, rejectedBy) {
  logStore.addLog(
    'ADS',
    'Ad Rejected',
    `Business: ${businessName}; Reason: ${reason}; Rejected by: ${rejectedBy}`,
    'SUCCESS'
  );
}

// ===== GLOBAL LOG ACTIVITY FUNCTION =====
window.logActivity = function(category, action, status = 'SUCCESS', details = '') {
  logStore.addLog(category, action, details, status);
};

// ===== GET LOGS FOR DISPLAY =====
window.getLogsForDisplay = function(filters = {}) {
  return logStore.filterLogs(filters);
};

// ===== EXPORT LOGS =====
window.exportLogs = function(format = 'json') {
  const logs = logStore.getAllLogs();
  
  if (format === 'csv') {
    let csv = 'Date,Time,Category,Action,Details,Status,Member\n';
    logs.forEach(log => {
      csv += `"${log.date}","${log.time}","${log.category}","${log.action}","${log.details}","${log.status}","${log.memberName}"\n`;
    });
    return csv;
  }
  
  return JSON.stringify(logs, null, 2);
};

// ===== PRINT LOGS =====
window.printLogs = function(filters = {}) {
  const logs = logStore.filterLogs(filters);
  const printWindow = window.open('', '', 'height=600,width=800');
  
  let html = `
    <html>
      <head>
        <title>Indian Club Bahrain - Activity Logs</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          h1 { color: #333; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #667eea; color: white; }
          tr:nth-child(even) { background-color: #f9f9f9; }
          .success { color: #2ed573; }
          .warning { color: #ffa502; }
          .failed { color: #ff6b6b; }
        </style>
      </head>
      <body>
        <h1>Indian Club Bahrain - Activity Logs</h1>
        <p>Generated: ${new Date().toLocaleString()}</p>
        <p>Total Records: ${logs.length}</p>
        <table>
          <thead>
            <tr>
              <th>Date & Time</th>
              <th>Category</th>
              <th>Action</th>
              <th>Details</th>
              <th>Status</th>
              <th>Member</th>
            </tr>
          </thead>
          <tbody>
  `;
  
  logs.forEach(log => {
    const statusClass = log.status === 'SUCCESS' ? 'success' : log.status === 'WARNING' ? 'warning' : 'failed';
    html += `
      <tr>
        <td>${log.date} ${log.time}</td>
        <td>${log.category}</td>
        <td>${log.action}</td>
        <td>${log.details}</td>
        <td class="${statusClass}">${log.status}</td>
        <td>${log.memberName}</td>
      </tr>
    `;
  });
  
  html += `
          </tbody>
        </table>
      </body>
    </html>
  `;
  
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.print();
};

// ===== CLEAR OLD LOGS (Keep last 90 days) =====
window.clearOldLogs = function() {
  const ninetyDaysAgo = new Date();
  ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90);
  
  logStore.logs = logStore.logs.filter(log => {
    return new Date(log.timestamp) > ninetyDaysAgo;
  });
  
  localStorage.setItem('clubLogs', JSON.stringify(logStore.logs));
  console.log('✅ Old logs cleared (kept last 90 days)');
};

console.log('✅ logs.js loaded successfully');

